// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-wallet.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_wallet_default = defineTool({
  name: "get_my_wallet",
  title: "Get my wallet balance",
  description: "Return the signed-in employee's wallet balance and recent balance metadata from Great Pearl Coffee.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on token" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.rpc("get_user_balance_safe", { user_email: email });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const balance = Number(data?.wallet_balance ?? 0);
    return {
      content: [
        {
          type: "text",
          text: `Wallet balance for ${email}: UGX ${balance.toLocaleString()}`
        }
      ],
      structuredContent: { email, balance, raw: data }
    };
  }
});

// src/lib/mcp/tools/list-my-recent-approvals.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
var list_my_recent_approvals_default = defineTool2({
  name: "list_my_recent_approvals",
  title: "List my recent approval requests",
  description: "List the signed-in user's most recent approval requests (withdrawals, expenses, etc.) with status and amount.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many rows to return (1-50). Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on token" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("approval_requests").select("id, type, amount, status, created_at, description").eq("requestedby", email).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pudfybkyfedeggmokhco";
var mcp_default = defineMcp({
  name: "great-pearl-coffee-mcp",
  title: "Great Pearl Coffee MCP",
  version: "0.1.0",
  instructions: "Tools for the Great Pearl Coffee (Great Agro Coffee) operations app. All tools act as the signed-in employee via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_wallet_default, list_my_recent_approvals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
