CREATE OR REPLACE FUNCTION public.validate_source_category()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $function$
BEGIN
  IF NEW.source_category IS NOT NULL AND NEW.source_category NOT IN (
    'SELF_DEPOSIT','SYSTEM_AWARD','LOAN_DISBURSEMENT','LOAN_REPAYMENT',
    'TRANSFER_IN','INTERNAL_TRANSFER','SALARY','DAILY_SALARY','MONTHLY_SALARY',
    'EXPENSE_CREDIT','WITHDRAWAL','INSTANT_WITHDRAWAL','OVERDRAFT_DRAW','OVERDRAFT_FEE',
    'OVERDRAFT_RECOVERY','OVERDRAFT_INTEREST','OVERDRAFT_PENALTY',
    'LOAN_INTEREST','INTEREST_ACCRUAL','STATEMENT_FEE',
    'SALARY_ADVANCE_DISBURSEMENT','SALARY_ADVANCE_REPAYMENT',
    'WITHDRAW_FEE','GOSENTE_FEE','BUDGET_TRANSFER',
    'OTHER'
  ) THEN
    RAISE EXCEPTION 'Invalid source_category: %', NEW.source_category;
  END IF;
  RETURN NEW;
END;
$function$;